services:
  - type: web
    name: autotrade-backend
    env: node
    buildCommand: npm install && npm run build:api
    startCommand: npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: autotrade-db
          property: connectionString
    autoDeploy: true

  - type: pserv
    name: autotrade-db
    env: docker
    plan: free
    region: oregon
    image:
      url: postgres:15
    disk:
      name: postgres
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
    envVars:
      - key: POSTGRES_DB
        value: autotrade
      - key: POSTGRES_USER
        value: autotrade_user
      - key: POSTGRES_PASSWORD
        generateValue: true